version: '1.2'
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=A123A345A
      - POSTGRES_DB=pgdb